version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3000:3000"
    depends_on:
      - db
    
