
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: db

development:
  <<: *default
  database: blackjack_development

test:
  <<: *default
  database: blackjack_test

production:
  <<: *default
  database: blackjack_production
  host: <%= ENV['MYSQL_HOST'] %>
